name: s_link
description: A new Flutter project.
publish_to: 'none'
version: 3.2.8+71

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_messaging: ^16.1.0
  provider: ^6.1.5+1
  image_picker: ^1.2.1
  mobile_scanner: ^7.1.4
  qr_flutter: ^4.1.0
  firebase_storage: ^13.0.5
  geolocator: ^14.0.2
  geolocator_linux: ^0.2.3
  url_launcher: ^6.3.2
  collection: ^1.19.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  intl: ^0.20.2
  file_picker: ^10.3.7  # สำหรับเลือกไฟล์
  csv: ^7.1.0          # สำหรับอ่านไฟล์ CSV
  package_info_plus: ^9.0.0
  http: ^1.2.0
  connectivity_plus: ^7.0.0
  in_app_update: ^4.2.5
  flutter_local_notifications: ^20.1.0
  mysql_client: ^0.0.27
  shared_preferences: ^2.5.4
  audioplayers: ^6.5.1
  pdf: ^3.11.3
  printing: ^5.14.2
  excel: ^4.0.6
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  flutter_native_splash: ^2.4.4
  cached_network_image: ^3.4.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 28

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo.png"
  android_12:
    image: "assets/images/logo.png"
    icon_background_color: "#ffffff"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/sounds/